name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2  # or your preferred Poetry version

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build distributions with Poetry
        run: poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write  # Required for trusted publishing (no token needed)

    environment:
      name: pypi
      # Optional: update to reflect your project
      # url: https://pypi.org/project/YOURPROJECT
      # or
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish to PyPI via trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
